### ISSUE TITLE
Jury

### ISSUE THREAD

**Issue by yuriidanyliak** [lkde/lkde.github.io#1]
Please, enroll me as developer!

City: Lvov

**Comment by midenok** [comment]
Please, follow the [instructions](https://github.com/lkde/git/wiki/Building-KDE4-from-Git-repository) of building KDE4. If you have any questions -- feel free to ask.

**Comment by yuriidanyliak** [comment]
working on a task: need to update my system (Ubuntu 12.04), because cmake 2.8.9 or higher is required to build KDE4.
will inform about results

**Comment by midenok** [comment]
It is pretty easy if you know how to work with [aptitude](https://wiki.debian.org/Aptitude). I probably should write a small tutorial about it. So, if you need any directions, please give me a note.

**Comment by yuriidanyliak** [comment]
I already know how to do this, at least, theoretically. If I will stumped in this task, finally I will call you for help.

**Comment by midenok** [comment]
Ok. Just be cautious of bottom line and keys 'e' and '!' -- they will help you to resolve conflicts. How to switch repository is described in [p.3](https://github.com/lkde/git/wiki/Building-KDE4-from-Git-repository#3-ensure-you-have-latest-linux-distribution-release).

**Comment by midenok** [comment]
Hi! I would like to know how the business is going. If you need a skype chat to get personal instructions, you can find me by my nickname.
