### ISSUE TITLE
Vlad

### ISSUE THREAD

**Issue by club11** [lkde/lkde.github.io#10]
Please, enroll me as developer! 

My experience:  c++/stl

My city:
Minsk
Backrgound info:I am a novice , but I have a great desire to gain experience.

**Comment by midenok** [comment]
Привет! [kdevelop откомпилировать](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository) можешь?

**Comment by midenok** [comment]
Hello!

Thank you for your interest! I am sorry for a little delay.
The scheme for you to contribute and learn is following:
1. [Compile KDevelop](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository)
2. Choose bug [from my list](https://bugs.kde.org/buglist.cgi?order=Importance&emailreporter1=1&emailtype1=substring&query_format=advanced&bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=ASSIGNED&bug_status=REOPENED&email1=midenok&product=kdevelop) or [from the whole list](https://bugs.kde.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=ASSIGNED&bug_status=REOPENED&list_id=1373848&order=Importance&product=kdevelop&query_format=advanced)
3. Analyze code to find the changes required for fixing the bug

On any stage you can ask any questions here. I hope, I will be more responsive from now!

Good luck!
