### ISSUE TITLE
Vladimir Mironiuk

### ISSUE THREAD

**Issue by VMironiuk** [lkde/lkde.github.io#12]
Please, enroll me as developer!

My experience: developing desktop apps with C++/Qt about 2 years

My city: Vinnytsia (Ukraine)

Background info: In present time working at Silego Technology.

**Comment by midenok** [comment]
Привет! [kdevelop откомпилировать](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository) можешь?

**Comment by VMironiuk** [comment]
Привет! Бренч stable скомпилил, trunk немного позже попробую.

2015-11-06 14:17 GMT+02:00 midenok notifications@github.com:

**Comment by midenok** [comment]
Обновил инфу о компиляции development версии. Если были какие-то затыки со stable, пожалуйста укажи.

**Comment by midenok** [comment]
Насчёт development версии -- некоторых версий пакетов (kdevplatform-dev 4.90.90) ещё нет в Ubuntu и Debian, но есть в ArchLinux. Поэтому можно не заморачиваться сильно с development версией. Начинать работать можно на стабильной.

**Comment by VMironiuk** [comment]
На шаге build stable/kdevelop вылезала ошибка (см. прикрепленный файл).

7 ноября 2015 г., 8:51 пользователь midenok notifications@github.com
написал:

**Comment by midenok** [comment]
Не вижу прикрепленный файл. Пожалуйста, используй синтаксис ``` для вставки текста в комментарии Github.

**Comment by midenok** [comment]
Не вижу прикрепленный файл. Пожалуйста, используй синтаксис ``` для вставки текста в комментарии Github.

**Comment by VMironiuk** [comment]
Ах да, извини, я через gmail писал. Вот ошибка:

```
failed to create symbolic link '/home/vovan/src/kde/kdevelop/stable/opt/share/apps/plasma/plasmoids/kdevelopsessions/' because existing path cannot be removed: Is a directory
CMake Error at /home/vovan/src/github/ln-install/CMake/linked_install.cmake:35 (message):
  create_symlink failed!
  old:/home/vovan/src/kde/kdevelop/stable/kdevelop/app/plasma/applet/package/
  new:/home/vovan/src/kde/kdevelop/stable/opt/share/apps/plasma/plasmoids/kdevelopsessions/
Call Stack (most recent call first):
  /home/vovan/src/github/ln-install/CMake/linked_install.cmake:74 (symlink)
  app/plasma/applet/cmake_install.cmake:44 (file)
  app/plasma/cmake_install.cmake:38 (include)
  app/cmake_install.cmake:156 (include)
  cmake_install.cmake:44 (include)


Makefile:66: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by midenok** [comment]
Да, это ошибка в [моём скрипте](https://github.com/midenok/ln-install/blob/master/CMake/linked_install.cmake) (строка 36). Поможешь отладить? Дело в том, что аргумент `${src}` неожиданно директория (`/home/vovan/src/kde/kdevelop/stable/kdevelop/app/plasma/applet/package/`). Я на такое не рассчитывал (и [дока](https://cmake.org/cmake/help/v3.0/command/file.html) вроде тоже). Нужно найти как выглядела изначальная команда (make VERBOSE=1 install). И правда ли она передала в FILE INSTALL аргументом директорию?

**Comment by VMironiuk** [comment]
Хорошо, попробую разобраться.
