### ISSUE TITLE
Vladislav

### ISSUE THREAD

**Issue by endiny** [lkde/lkde.github.io#13]
Please, enroll me as developer!

My experience: Small C++ Experience, and very little Qt exp.

My city: St. Petersburg

Backrgound info: Mercurial, Jenkins, CUnit, WinAPI, .NET (Basic)

**Comment by midenok** [comment]
Привет! [kdevelop откомпилировать](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository) можешь?

**Comment by endiny** [comment]
Просто сбилдить смогу, наверное. А зачем?

**Comment by midenok** [comment]
Цели немного поменялись: сейчас не столько важна "легковесность" KDE, поскольку это вполне осуществимо при помощи конфигурации, сколько качество самого софта. А софт у KDE, если честно _больной на всю голову_. Для начала хотелось бы исправить косяки в самом KDevelop, поскольку это самая используемая (мной по крайней мере) программа, а затем уже взяться за десктоп.
