### ISSUE TITLE
kazancev m sergey

### ISSUE THREAD

**Issue by kazancevsm** [lkde/lkde.github.io#2]
Пожалуйста зарегистрируйте меня в качестве разработчика!

Мой опыт: разработка сайтов, разарботка плагинов - 10 лет. Сижу на линуксе уже 10 лет, поклонник kde 3.

Мой город: Сухой Лог, Свердловская область.

Дополнительная информация:
1) На хорошем уровне html, css, mysql.
2) На среднем уровне php - плотно начал изучать год назад.
3) Баловался с qt designer и qt developer.
4) Слепая печать на русском.
5) Знание очень многих линукс приложений
6) Хороший уровень владения графикой Gimp, Inkskape
7) В свое время изучал basic, паскаль, визуал бейсик

Мои пробелы:
Не писал не разу программы под linux

Моя цель в проекте
освоить c, c++, xml - в идеале.
принимать учасите в разработке данного проекта,
научиться компилировать код,
научится делать сборки дистрибутивов,
получить интересное общение и опыт

**Comment by midenok** [comment]
Добро пожаловать!

Начинать можно вот отсюда: https://github.com/lkde/git/wiki/Building-KDE4-from-Git-repository
Проследуй пожалуйста до 4-го пункта включительно, затем свяжись со мной.

Мой скайп: midenok

Если будут какие-то вопросы по ходу работы -- не стесняйся спрашивать.

**Comment by midenok** [comment]
Предлагаю на этой неделе выйти на видеосвязь втроём, чтобы обсудить текущие проблемы. Я могу после 19 мск.

И скажи пожалуйста свой Skype.
