### ISSUE TITLE
Александр всегда готов участвовать

### ISSUE THREAD

**Issue by stalker-people** [lkde/lkde.github.io#3]
_|Ru Version__________
Здраствуйте, я хочу участвовать в вашем проекте. Ваша идея мне понравилась.
Моя манна, опыт, xp: знание php, html, css, mysql, pascal. Основы юзания редакторов графики есть, установку системы Linux производил. Основы консоли есть. В дальнейшем буду изучать ЯП с использованим библиотеки Qt4.
Мой 1-ый E-mail: lebedyev-chernobylru@yandex.ru
Мой 2-ой E-mail: chernleb@gmail.com
И ещё я есть в ВКонтакте: http://vk.com/chern_leb
## Проживаю в Сухом Логу

_|En Version_________________
Please, enroll me as developer!

My experience: 5009 xp :D
My first E-mail: lebedyev-chernobylru@yandex.ru
My second E-mail: chernleb@gmail.com
My city: Suhoy Log

**Comment by midenok** [comment]
Сегодня день нашествия Сухого Лога!
ЯП это что, "Я Плакал"?

Добро пожаловать на борт!

Пожалуйста, [следуй](https://github.com/lkde/git/wiki/Building-KDE4-from-Git-repository) до п. 4 включительно, затем ко мне на ковёр.

Мой скайп: midenok

Если будут какие-то вопросы по ходу работы -- не стесняйся спрашивать!

**Comment by stalker-people** [comment]
Пусть даже и так :trollface:

**Comment by kazancevsm** [comment]
Да, это нашествие Сухого Лога, и это похоже еще не все ;-)

**Comment by midenok** [comment]
Предлагаю на этой неделе выйти на видеосвязь втроём, чтобы обсудить текущие проблемы. Я могу после 19 мск.

**Comment by kazancevsm** [comment]
Я компьютер настроил на последней кубунте и вроде 4 шага проделал. Можно будет связаться, предлагаю в пятницу в районе с 19 00 - 20 00 по МСК создать видеосвязь. Получится нет?

**Comment by midenok** [comment]
Думаю, 19:30 будет вполне приемлемым.

**Comment by stalker-people** [comment]
Извините, а можно поддерживать связь в районе 16:00 по МСК? А то в 9 вечера неудобно)

**Comment by midenok** [comment]
Реал-тайм -- очень недолго. Тогда лучше пошагово.
