### ISSUE TITLE
Vlad

### ISSUE THREAD

**Issue by mechanician** [lkde/lkde.github.io#4]
Please, enroll me as developer!

My experience: 
I've been programming with C/C++ for several years.
Most of projects were scientific (Numerical methods in gas dynamics, magneto hydro dynamics and hydrodynamics). Also I was working in Roxar company for almost a year as developer (C++ with Qt).
Also I am familiar with Python.

My city: 
Moscow, Russia

Background info:
Actually, I do not have a plenty of time but I'd like to spend several hours a week
for some open source project to keep sharp and improve my programming skills and, of course, to make some contribution for open source society.

Thanks in advance!

**Comment by midenok** [comment]
Hi! Do you use KDE3 on everyday basis or is it just the sake of pure practice? I'm asking because KDE3-4 programming on 70% is struggle with compilation. Not very attractive for one who just wants to boost C++ skill.

**Comment by mechanician** [comment]
Yes, I use KDE4.

**Comment by midenok** [comment]
Please, get familiar with [this](https://github.com/lkde/edu/issues/4) ticket. If you are fine with the idea of porting KDE3 Kicker into KDE4, I will make a further instructions on preparation of build environments for KDE3 and KDE4.

**Comment by mechanician** [comment]
I apologize for the late answer. 
The idea seems somewhat challenging but, nevertheless, interesting)
I'm looking forward to your next instructions.
