### ISSUE TITLE
Сергей

### ISSUE THREAD

**Issue by glavposhtamt** [lkde/lkde.github.io#5]
Please, enroll me as developer!

Работал web-программистом, с начала этого года переключился на C/C++, писал несложные программы для себя.

My city: Симферополь

Backrgound info: 
skype: phpsite_creator
e-mail: glavposhtamt@bk.ru
Хочу участвовать в проекте для того чтобы совершенствовать свои навыки в программировании.

**Comment by midenok** [comment]
Ok, but bear in mind, that [objectives](https://github.com/lkde/lkde.github.io/wiki) are changed. First priority is fix [bugs](https://bugs.kde.org/buglist.cgi?order=Importance&emailreporter1=1&emailtype1=substring&query_format=advanced&bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=ASSIGNED&bug_status=REOPENED&email1=midenok&product=kdevelop) in KDevelop. I will prepare instructions of how to compile KDevelop. Meanwhile, you can try to do it yourself.

**Comment by midenok** [comment]
[Here are](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository) instructions to build KDevelop. Please, follow them and tell me if there is something wrong. Please, confirm.

P.S. But before make sure, that you are [using Github via SSH](https://github.com/learn-it/git/issues/1)!

**Comment by midenok** [comment]
Are you here?

**Comment by glavposhtamt** [comment]
I don`t speak English

**Comment by midenok** [comment]
Ты можешь писать на русском если хочешь, но основные инструкции будут на английском. Ты в состоянии их прочитать?

**Comment by glavposhtamt** [comment]
24.06.2014 16:44, midenok пишет:

> Here are 
> https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository 
> instructions to build KDevelop. Please, follow them and tell me if 
> there is something wrong. Please, confirm.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/lkde/lkde.github.io/issues/5#issuecomment-46965759.
> 
> Я когда солашался участвовать в этом проекте, надеялся, что меня научат 
> чему-то новому (Так было написано на форуме). Мне до сих пор хочется 
> развиваться и пытаться выполнять какую-нибудь работу, но не могли бы вы 
> по-русски обьяснить с чего мне начать, как начать. Какие задания 
> выполнять и куда обращаться с вопросами, может у вас есть skype, с 
> помощью. которого можно обсудить технические вопросы на русском. Ни разу 
> просто ещё ни участвовал в таких проектах.

P.S. Есть опыт работы с git, OS Ubuntu, знание STL и QT.

**Comment by midenok** [comment]
Но, разве здесь нельзя обсудить технические вопросы? Что-то очень сложное можно и по скайпу -- если оно возникнет. Далее. Разве [здесь](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository) нет ничего нового? Предлагаю начать с этого задания.

Теперь насчёт английского. Человек изучает C++ в среде Unix, а английский не изучает. Это как вообще? А по Git, STL и QT на русском документация где и какого качества?

**Comment by glavposhtamt** [comment]
В основном пользовался google-переводчиком и русской версией man. С 
сегодняшнего дня начал учить английский. Домой приеду, возьмусь за работу.
