### ISSUE TITLE
Руслан

### ISSUE THREAD

**Issue by microinginer** [lkde/lkde.github.io#6]

**Comment by midenok** [comment]
Ok, but bear in mind, that [objectives](https://github.com/lkde/lkde.github.io/wiki) are changed. First priority is fix [bugs](https://bugs.kde.org/buglist.cgi?order=Importance&emailreporter1=1&emailtype1=substring&query_format=advanced&bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=ASSIGNED&bug_status=REOPENED&email1=midenok&product=kdevelop) in KDevelop. I will prepare instructions of how to compile KDevelop. Meanwhile, you can try to do it yourself.

**Comment by midenok** [comment]
[Here are](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository) instructions to build KDevelop. Please, follow them and tell me if there is something wrong. Please, confirm.

P.S. But before make sure, that you are [using Github via SSH](https://github.com/learn-it/git/issues/1)!

**Comment by midenok** [comment]
Are you here?

**Comment by microinginer** [comment]
yep I'm here

**Comment by midenok** [comment]
Итак?
