### ISSUE TITLE
Sergey Nikiforov

### ISSUE THREAD

**Issue by Sdelan-v-CCCP** [lkde/lkde.github.io#7]
Please, enroll me as developer!

My experience:
В настоящий момент, опыт программирования на С пол года. С++ синтаксис уже подзабыл, нужно повторить. Linux тоже пол года. Английский могу только читать, писать пока еще очень плохо получается.  Есть ОГРОМНОЕ желание участвовать в крупных Open Source проектах. Пришел по ссылке отсюда http://kde.ru/xforum/index.php?PHPSESSID=fed86b6d5f2686453acbe98d5698f73d&topic=515.0

My city:
Россия, Республика Башкортостан, Уфа 

Backrgound info:
nikser91@gmail.com

**Comment by midenok** [comment]
Ok, Вы приняты. На данный момент актуально исправление багов в kdevelop. Предлагаю начать с настройки окружения разработки. Всё необходимое я Вам предоставлю. Пожалуйста, ознакомьтесь с [этим](https://bugs.kde.org/show_bug.cgi?id=335470) багом.

Следуйте [инструкции](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository). Скрипт `prepare` (из п.2) довольно старый и считает стабильной версию 4.6, хотя сейчас уже выпущена 4.7. Предлагаю Вам также изучить что делает скрипт и настроить его на компиляцию 4.7.

Пожалуйста, подтвердите Ваше согласие и будьте со мной в тесном контакте -- так быстрее будет двигаться дело. Если что-то неясно, не стесняйтесь задавать вопросы. Жду Ваш ответ в течении следующей недели.

**Comment by Sdelan-v-CCCP** [comment]
ОК! У меня пока на работе небольшой аврал. Постараюсь в течении недели разобраться. Вопросы в конце недели. Как же без них :)

**Comment by Sdelan-v-CCCP** [comment]
Я не смог пройти пункт 4 (build stable/kdevplatform:)
Вышло вот такое.
 ./cmake.sh: line 7: cmake-ln: команда не найдена

И на счет изменения версии до 4.7. Достаточно ли просто изменить в строчке ниже 4.6 на 4.7?
    git checkout -b stable remotes/origin/4.6

(скрипт prepare)

**Comment by midenok** [comment]
Смотрите скрипт [install-li](https://raw.githubusercontent.com/lkde/edu/master/scripts/install-li) (п. 1). Он устанавливает `cmake-ln` в `$HOME/bin`. Проверьте `$PATH`. Насколько я помню, для того чтобы `$HOME/bin` добавился `PATH` достаточно запустить новую сессию `bash`, ну или сделать `source ~/.profile`. Или просто сделать `PATH=$HOME/bin:$PATH`.

Насчёт 4.7. Я бы сначала посмотрел есть ли такая ветка в git. Но если не знаете как, можно просто попробовать заменить и посмотреть что получится.

**Comment by Sdelan-v-CCCP** [comment]
Все собралось. Тупанул так тупанул я в прошлый раз. 
Но теперь у меня вот такая вещь, я не знаю где исправить строчочку.
Это при выполнении: Repeat step 4. for kdevelop.
- Symlinking: /home/mranderson/src/kde/kdevelop/stable/opt/lib/kde4/plasma_engine_kdevelopsessions.so
  -- Symlinking: /home/mranderson/src/kde/kdevelop/stable/opt/share/kde4/services/plasma-dataengine-kdevelopsessions.desktop
  -- Symlinking: /home/mranderson/src/kde/kdevelop/stable/opt/share/apps/plasma/services/org.kde.plasma.dataengine.kdevelopsessions.operations
  failed to create symbolic link '/home/mranderson/src/kde/kdevelop/stable/opt/share/apps/plasma/plasmoids/kdevelopsessions/' because existing path cannot be removed: Is a directory

**Comment by midenok** [comment]
Возможно, какой-то конфликт в `cmake-ln`. Я тестировал на 4.6. На 4.6 собирается? Как Вы уже наверное догадались `cmake-ln` это мой грязно-хакерский враппер для установки симлинков. Соответственно, наверное что-то там несовместимо. Это надо мне проверять. Вы пока можете использовать просто `cmake`, он будет просто копировать файлы, как и положено при нормальной инсталляции.

**Comment by Sdelan-v-CCCP** [comment]
Я все делал на 4.6 (как раз там это ошибка вылезла). Для меня главное пока хоть что-то собрать. Потом уже буду пробовать 4.7

**Comment by midenok** [comment]
Получилось с `cmake`?

**Comment by Sdelan-v-CCCP** [comment]
С cmake все получилось.

**Comment by midenok** [comment]
Ну и отлично! Пока нет активной разработки, это не принцпиально.
Теперь, смотрите `kdevelop.sh`. Там есть строчка:

```
$optdir/bin/kdevelop "$@"
```

Поменяйте на

```
gdb --args $optdir/bin/kdevelop "$@"
```

Запускайте

```
./kdevelop.sh stable
```

Затем в gdb:

```
start
```

Затем

```
run
```

Если после `run` откроется рабочее окно кдевелопа, значит всё круто!

**Comment by Sdelan-v-CCCP** [comment]
У меня не создается папка opt. Все сразу копируется в /usr/bin, kdevelop оттуда запускается.

**Comment by midenok** [comment]
Вы в `cmake.sh` заменили `cmake-ln` на `cmake`, а затем запустили `cmake.sh`?

**Comment by Sdelan-v-CCCP** [comment]
Нет, я вместо cmake.sh выполнил просто cmake. Дома буду, сделаю по вашему.

**Comment by midenok** [comment]
Ну так, очевидно, `cmake` без параметров настроит всё по-умолчанию.

**Comment by Sdelan-v-CCCP** [comment]
Все заработало. Запустил в gdb.

**Comment by midenok** [comment]
Ок. Теперь фиксим [баг](https://github.com/lkde/kdevelop/issues/1).
