### ISSUE TITLE
Dmitry Dmitriev

### ISSUE THREAD

**Issue by dmdmal** [lkde/lkde.github.io#8]
Please, enroll me as developer!

My experience: >1 year

My city: Voronezhskaya obl, city Kalach

Backrgound info: mastering Qt, boost

**Comment by midenok** [comment]
Ok, Вы приняты. На данный момент актуально исправление багов в kdevelop. Предлагаю начать с настройки окружения разработки. Всё необходимое я Вам предоставлю. Пожалуйста, ознакомьтесь с [этим](https://bugs.kde.org/show_bug.cgi?id=338290) багом.

Следуйте [инструкции](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository). Скрипт `prepare` (из п.2) довольно старый и считает стабильной версию 4.6, хотя сейчас уже выпущена 4.7. Предлагаю Вам также изучить что делает скрипт и настроить его на компиляцию 4.7.

Пожалуйста, подтвердите Ваше согласие и будьте со мной в тесном контакте -- так быстрее будет двигаться дело. Если что-то неясно, не стесняйтесь задавать вопросы. Жду Ваш ответ в течении недели.

**Comment by dmdmal** [comment]
У меня несколько проблем первая - нет прав на загрузку через скрипт install-li, и вторая я не могу определить версию kdevelop. И еще, зависимости от kdevelop версии 4.6 подойдут?

**Comment by midenok** [comment]
Зависимости от kdevelop 4.6 скорее всего подойдут. Сейчас в Ubuntu уже появилась версия 4.7. Вывод скрипта можно увидеть?

**Comment by dmdmal** [comment]
Можно, но только завтра, так как компьютер с Linux, на данный момент только на работе, потому что домашний ноут на гарантиию. В Gentoo еще актуальная версия 4.5, а 4.6 в не стабильной еще, 4.7 вообще нету, а стянуть руками 4.7 к сожалению еще ума не хватает...

**Comment by dmdmal** [comment]
Вот сам вывод скрипта

Cloning into /home/dmdmal/src/github/ln-install...

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by midenok** [comment]
[Сделайте это.](https://github.com/learn-it/git/issues/1)

**Comment by dmdmal** [comment]
У меня почему-то не собрался исполняемый файл kdevelop, в директории opt/bin/ всего 3 файла 2 скриптовых и 1 исполняемый - kdev_dbus_socket_transformer

**Comment by dmdmal** [comment]
Все разобрался, пакетов не доставало, под отладчиком запустил kdevelop

**Comment by midenok** [comment]
Здорово! Теперь фиксим [баг](https://github.com/lkde/kdevelop/issues/2).
