### ISSUE TITLE
Pavel

### ISSUE THREAD

**Issue by p-orlov** [lkde/lkde.github.io#9]
Please, enroll me as developer!

My experience: 1 year (C++)

My city: Chelyabinsk

Backrgound info: want to learn Qt

**Comment by midenok** [comment]
Здравствуйте! На данный момент актуально исправление багов в kdevelop. Предлагаю начать с настройки окружения разработки.

Следуйте [инструкции](https://github.com/lkde/edu/wiki/Building-KDevelop-from-Git-repository). 

Пожалуйста, подтвердите Ваше согласие. Если что-то неясно, не стесняйтесь задавать вопросы.
